### ISSUE TITLE
User management + Traffic limitation + expire date

### ISSUE THREAD

**Issue by zerodwide** [ShadowsocksR-Live/shadowsocksr-native#243]
Hi Guys

does SSROT support any kind of: User management + Traffic limitation + expire date?
still it is undetectable in IRAN, whereas Xray XTLS are suffering upload speed throttling! 

Thanks

**Comment by ssrlive** [comment]
Since this project is written in C language, it is difficult to maintain and add new features, so I have not planned to spend energy on this project. You can try my new toy [overtls](https://github.com/ssrlive/overtls) , which is written in rust, has extremely simple and direct code implementation, and strong expansion capabilities. I will add user management functions to `overtls` in the future.

**Comment by zerodwide** [comment]
@ssrlive Thanks a lot <3
